Updates to add descriptions, better usage docs, and validate with shellcheck.

diff --git a/commands/git-del b/commands/git-del
--- a/commands/git-del
+++ b/commands/git-del
@@ -1,10 +1,19 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
+# Originally taken from [visionmedia/git-extras](https://github.com/visionmedia/git-extras) (MIT License).
 
-# Originally taken from
-# [visionmedia/git-extras](https://github.com/visionmedia/git-extras)
-# (MIT License).
+##
+# Deletes a branch, both locally and on the remote origin.
+#
+# Usage:
+#   git contains {hash}
+##
 
-branch=$1
-test -z "$branch" && echo "branch required." 1>&2 && exit 1
-git branch -D "$branch"
-git branch -d -r "origin/$branch" && git push origin :"$branch"
+branch="$1"
+
+if [[ -z "${branch}" ]]; then
+    echo "Branch name is required." >&2
+    exit 1
+fi
+
+git branch -D "${branch}"
+git branch -d -r "origin/${branch}" && git push origin :"${branch}"
diff --git a/commands/git-delta b/commands/git-delta
--- a/commands/git-delta
+++ b/commands/git-delta
@@ -1,30 +1,36 @@
 #! /usr/bin/env bash
-
-# Copyright (c) 2014-2021 Ryan Parman <http://ryanparman.com>
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in
-# all copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-# THE SOFTWARE.
-#
+# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
 # http://opensource.org/licenses/MIT
 
+##
+# Shows the commits from the current branch which are not in the specified branch.
+#
 # Usage:
-#   git delta $branch
+#   git delta <branch>
+##
 
-git cherry -v "$1" master | grep '^+' | awk '{print $2}' | xargs git show \
+current_branch="$(git rev-parse --abbrev-ref HEAD)"
+compared_branch="$1"
+
+if [[ -z "${current_branch}" ]]; then
+    echo "You do not appear to be on a branch." >&2
+    exit 1
+fi
+
+if [[ -z "${compared_branch}" ]]; then
+    echo "Branch name is required." >&2
+    exit 1
+fi
+
+if [[ ${current_branch} == "${compared_branch}" ]]; then
+    echo "You cannot compare a branch to itself." >&2
+    exit 1
+fi
+
+results="$(git cherry -v "${compared_branch}" "${current_branch}")"
+results="$(echo "${results}" | grep '^+')"
+results="$(echo "${results}" | awk '{print $2}')"
+
+echo "${results}" | xargs git show \
     --pretty=format:'%C(red)%H%C(reset) %C(yellow)%d%C(reset) %s [%C(green)%an, %C(bold black)%cr%C(reset)]' \
     --summary --no-patch --color --decorate --stat --abbrev-commit --date=relative
